name: Check Formatting
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Setup Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt, clippy

      - name: Setup Rust cache
        uses: Swatinem/rust-cache@v2
        with:
          workspaces: |
            bindings

      - name: Check Rust formatting
        run: cargo fmt --manifest-path bindings/Cargo.toml --check

      - name: Check clippy
        run: cargo clippy --manifest-path bindings/Cargo.toml -- --deny warnings
